<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/attendance_table.php');
	include_once(__DIR__ . '/attendance_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('attendance_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'attendance_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`attendance_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`students_table1`.`id`) || CHAR_LENGTH(`students_table1`.`name`), CONCAT_WS('',   `students_table1`.`id`, ' ~ ', `students_table1`.`name`), '') /* Student Details */" => "student_details",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"if(`attendance_table`.`date`,date_format(`attendance_table`.`date`,'%d/%m/%Y'),'')" => "date",
		"`attendance_table`.`status`" => "status",
		"`attendance_table`.`created_by`" => "created_by",
		"`attendance_table`.`created_at`" => "created_at",
		"`attendance_table`.`last_updated_by`" => "last_updated_by",
		"`attendance_table`.`last_updated_at`" => "last_updated_at",
		"`attendance_table`.`created_by_username`" => "created_by_username",
		"`attendance_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`attendance_table`.`id`',
		2 => 2,
		3 => 3,
		4 => '`attendance_table`.`date`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`attendance_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`students_table1`.`id`) || CHAR_LENGTH(`students_table1`.`name`), CONCAT_WS('',   `students_table1`.`id`, ' ~ ', `students_table1`.`name`), '') /* Student Details */" => "student_details",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"if(`attendance_table`.`date`,date_format(`attendance_table`.`date`,'%d/%m/%Y'),'')" => "date",
		"`attendance_table`.`status`" => "status",
		"`attendance_table`.`created_by`" => "created_by",
		"`attendance_table`.`created_at`" => "created_at",
		"`attendance_table`.`last_updated_by`" => "last_updated_by",
		"`attendance_table`.`last_updated_at`" => "last_updated_at",
		"`attendance_table`.`created_by_username`" => "created_by_username",
		"`attendance_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`attendance_table`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`students_table1`.`id`) || CHAR_LENGTH(`students_table1`.`name`), CONCAT_WS('',   `students_table1`.`id`, ' ~ ', `students_table1`.`name`), '') /* Student Details */" => "Student Details",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "Subject Details",
		"`attendance_table`.`date`" => "Date",
		"`attendance_table`.`status`" => "Status",
		"`attendance_table`.`created_by`" => "Created by",
		"`attendance_table`.`created_at`" => "Created At",
		"`attendance_table`.`last_updated_by`" => "Last Updated by",
		"`attendance_table`.`last_updated_at`" => "Last Updated At",
		"`attendance_table`.`created_by_username`" => "Created by username",
		"`attendance_table`.`last_updated_by_username`" => "Last Updated By",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`attendance_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`students_table1`.`id`) || CHAR_LENGTH(`students_table1`.`name`), CONCAT_WS('',   `students_table1`.`id`, ' ~ ', `students_table1`.`name`), '') /* Student Details */" => "student_details",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"if(`attendance_table`.`date`,date_format(`attendance_table`.`date`,'%d/%m/%Y'),'')" => "date",
		"`attendance_table`.`status`" => "status",
		"`attendance_table`.`created_by`" => "created_by",
		"`attendance_table`.`created_at`" => "created_at",
		"`attendance_table`.`last_updated_by`" => "last_updated_by",
		"`attendance_table`.`last_updated_at`" => "last_updated_at",
		"`attendance_table`.`created_by_username`" => "created_by_username",
		"`attendance_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['student_details' => 'Student Details', 'subject_details' => 'Subject Details', ];

	$x->QueryFrom = "`attendance_table` LEFT JOIN `students_table` as students_table1 ON `students_table1`.`id`=`attendance_table`.`student_details` LEFT JOIN `subject_table` as subject_table1 ON `subject_table1`.`id`=`attendance_table`.`subject_details` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'attendance_table_view.php';
	$x->TableTitle = 'Attendance - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`attendance_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Student Details', 'Subject Details', 'Date', 'Status', 'Created by', 'Created At', 'Last Updated by', 'Last Updated At', ];
	$x->ColFieldName = ['student_details', 'subject_details', 'date', 'status', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/attendance_table_templateTV.html';
	$x->SelectedTemplate = 'templates/attendance_table_templateTVS.html';
	$x->TemplateDV = 'templates/attendance_table_templateDV.html';
	$x->TemplateDVP = 'templates/attendance_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: attendance_table_init
	$render = true;
	if(function_exists('attendance_table_init')) {
		$args = [];
		$render = attendance_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: attendance_table_header
	$headerCode = '';
	if(function_exists('attendance_table_header')) {
		$args = [];
		$headerCode = attendance_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: attendance_table_footer
	$footerCode = '';
	if(function_exists('attendance_table_footer')) {
		$args = [];
		$footerCode = attendance_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
