<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/courses_table.php');
	include_once(__DIR__ . '/courses_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('courses_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'courses_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`courses_table`.`id`" => "id",
		"`courses_table`.`course_name`" => "course_name",
		"IF(    CHAR_LENGTH(`departments_table1`.`id`) || CHAR_LENGTH(`departments_table1`.`department_name`), CONCAT_WS('',   `departments_table1`.`id`, '-', `departments_table1`.`department_name`), '') /* Department */" => "department",
		"if(`courses_table`.`starting_date`,date_format(`courses_table`.`starting_date`,'%d/%m/%Y'),'')" => "starting_date",
		"if(`courses_table`.`ending_date`,date_format(`courses_table`.`ending_date`,'%d/%m/%Y'),'')" => "ending_date",
		"`courses_table`.`duration`" => "duration",
		"`courses_table`.`credits`" => "credits",
		"`courses_table`.`created_by`" => "created_by",
		"`courses_table`.`created_at`" => "created_at",
		"`courses_table`.`last_updated_by`" => "last_updated_by",
		"`courses_table`.`last_updated_at`" => "last_updated_at",
		"`courses_table`.`created_by_username`" => "created_by_username",
		"`courses_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`courses_table`.`id`',
		2 => 2,
		3 => 3,
		4 => '`courses_table`.`starting_date`',
		5 => '`courses_table`.`ending_date`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`courses_table`.`id`" => "id",
		"`courses_table`.`course_name`" => "course_name",
		"IF(    CHAR_LENGTH(`departments_table1`.`id`) || CHAR_LENGTH(`departments_table1`.`department_name`), CONCAT_WS('',   `departments_table1`.`id`, '-', `departments_table1`.`department_name`), '') /* Department */" => "department",
		"if(`courses_table`.`starting_date`,date_format(`courses_table`.`starting_date`,'%d/%m/%Y'),'')" => "starting_date",
		"if(`courses_table`.`ending_date`,date_format(`courses_table`.`ending_date`,'%d/%m/%Y'),'')" => "ending_date",
		"`courses_table`.`duration`" => "duration",
		"`courses_table`.`credits`" => "credits",
		"`courses_table`.`created_by`" => "created_by",
		"`courses_table`.`created_at`" => "created_at",
		"`courses_table`.`last_updated_by`" => "last_updated_by",
		"`courses_table`.`last_updated_at`" => "last_updated_at",
		"`courses_table`.`created_by_username`" => "created_by_username",
		"`courses_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`courses_table`.`id`" => "ID",
		"`courses_table`.`course_name`" => "Course Name",
		"IF(    CHAR_LENGTH(`departments_table1`.`id`) || CHAR_LENGTH(`departments_table1`.`department_name`), CONCAT_WS('',   `departments_table1`.`id`, '-', `departments_table1`.`department_name`), '') /* Department */" => "Department",
		"`courses_table`.`starting_date`" => "Starting Date",
		"`courses_table`.`ending_date`" => "Ending Date",
		"`courses_table`.`duration`" => "Duration (In Year/Semester)",
		"`courses_table`.`credits`" => "Credits",
		"`courses_table`.`created_by`" => "Created by",
		"`courses_table`.`created_at`" => "Created At",
		"`courses_table`.`last_updated_by`" => "Last Updated by",
		"`courses_table`.`last_updated_at`" => "Last Updated At",
		"`courses_table`.`created_by_username`" => "Created by username",
		"`courses_table`.`last_updated_by_username`" => "Last Updated By",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`courses_table`.`id`" => "id",
		"`courses_table`.`course_name`" => "course_name",
		"IF(    CHAR_LENGTH(`departments_table1`.`id`) || CHAR_LENGTH(`departments_table1`.`department_name`), CONCAT_WS('',   `departments_table1`.`id`, '-', `departments_table1`.`department_name`), '') /* Department */" => "department",
		"if(`courses_table`.`starting_date`,date_format(`courses_table`.`starting_date`,'%d/%m/%Y'),'')" => "starting_date",
		"if(`courses_table`.`ending_date`,date_format(`courses_table`.`ending_date`,'%d/%m/%Y'),'')" => "ending_date",
		"`courses_table`.`duration`" => "duration",
		"`courses_table`.`credits`" => "credits",
		"`courses_table`.`created_by`" => "created_by",
		"`courses_table`.`created_at`" => "created_at",
		"`courses_table`.`last_updated_by`" => "last_updated_by",
		"`courses_table`.`last_updated_at`" => "last_updated_at",
		"`courses_table`.`created_by_username`" => "created_by_username",
		"`courses_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['department' => 'Department', ];

	$x->QueryFrom = "`courses_table` LEFT JOIN `departments_table` as departments_table1 ON `departments_table1`.`id`=`courses_table`.`department` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'courses_table_view.php';
	$x->TableTitle = 'Courses - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`courses_table`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Course Name', 'Department', 'Starting Date', 'Ending Date', 'Duration (In Year/Semester)', 'Credits', 'Created by', 'Created At', 'Last Updated by', 'Last Updated At', ];
	$x->ColFieldName = ['course_name', 'department', 'starting_date', 'ending_date', 'duration', 'credits', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/courses_table_templateTV.html';
	$x->SelectedTemplate = 'templates/courses_table_templateTVS.html';
	$x->TemplateDV = 'templates/courses_table_templateDV.html';
	$x->TemplateDVP = 'templates/courses_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: courses_table_init
	$render = true;
	if(function_exists('courses_table_init')) {
		$args = [];
		$render = courses_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: courses_table_header
	$headerCode = '';
	if(function_exists('courses_table_header')) {
		$args = [];
		$headerCode = courses_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: courses_table_footer
	$footerCode = '';
	if(function_exists('courses_table_footer')) {
		$args = [];
		$footerCode = courses_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
