<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/departments_table.php');
	include_once(__DIR__ . '/departments_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('departments_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'departments_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`departments_table`.`id`" => "id",
		"`departments_table`.`department_name`" => "department_name",
		"`departments_table`.`hod`" => "hod",
		"`departments_table`.`contact`" => "contact",
		"`departments_table`.`created_by`" => "created_by",
		"`departments_table`.`created_at`" => "created_at",
		"`departments_table`.`last_updated_by`" => "last_updated_by",
		"`departments_table`.`last_updated_at`" => "last_updated_at",
		"`departments_table`.`created_by_username`" => "created_by_username",
		"`departments_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`departments_table`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`departments_table`.`id`" => "id",
		"`departments_table`.`department_name`" => "department_name",
		"`departments_table`.`hod`" => "hod",
		"`departments_table`.`contact`" => "contact",
		"`departments_table`.`created_by`" => "created_by",
		"`departments_table`.`created_at`" => "created_at",
		"`departments_table`.`last_updated_by`" => "last_updated_by",
		"`departments_table`.`last_updated_at`" => "last_updated_at",
		"`departments_table`.`created_by_username`" => "created_by_username",
		"`departments_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`departments_table`.`id`" => "ID",
		"`departments_table`.`department_name`" => "Department Name",
		"`departments_table`.`hod`" => "Head of Department (HOD)",
		"`departments_table`.`contact`" => "Contact",
		"`departments_table`.`created_by`" => "Created by",
		"`departments_table`.`created_at`" => "Created At",
		"`departments_table`.`last_updated_by`" => "Last Updated by",
		"`departments_table`.`last_updated_at`" => "Last Updated At",
		"`departments_table`.`created_by_username`" => "Created by username",
		"`departments_table`.`last_updated_by_username`" => "Last Updated By",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`departments_table`.`id`" => "id",
		"`departments_table`.`department_name`" => "department_name",
		"`departments_table`.`hod`" => "hod",
		"`departments_table`.`contact`" => "contact",
		"`departments_table`.`created_by`" => "created_by",
		"`departments_table`.`created_at`" => "created_at",
		"`departments_table`.`last_updated_by`" => "last_updated_by",
		"`departments_table`.`last_updated_at`" => "last_updated_at",
		"`departments_table`.`created_by_username`" => "created_by_username",
		"`departments_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`departments_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'departments_table_view.php';
	$x->TableTitle = 'Departments - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`departments_table`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Department Name', 'Head of Department (HOD)', 'Contact', 'Created by', 'Created At', 'Last Updated by', 'Last Updated At', ];
	$x->ColFieldName = ['id', 'department_name', 'hod', 'contact', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/departments_table_templateTV.html';
	$x->SelectedTemplate = 'templates/departments_table_templateTVS.html';
	$x->TemplateDV = 'templates/departments_table_templateDV.html';
	$x->TemplateDVP = 'templates/departments_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: departments_table_init
	$render = true;
	if(function_exists('departments_table_init')) {
		$args = [];
		$render = departments_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: departments_table_header
	$headerCode = '';
	if(function_exists('departments_table_header')) {
		$args = [];
		$headerCode = departments_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: departments_table_footer
	$footerCode = '';
	if(function_exists('departments_table_footer')) {
		$args = [];
		$footerCode = departments_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
