<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/exams_table.php');
	include_once(__DIR__ . '/exams_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('exams_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'exams_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`exams_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"if(`exams_table`.`exam_date`,date_format(`exams_table`.`exam_date`,'%d/%m/%Y'),'')" => "exam_date",
		"`exams_table`.`exam_type`" => "exam_type",
		"`exams_table`.`created_by`" => "created_by",
		"`exams_table`.`created_at`" => "created_at",
		"`exams_table`.`last_updated_by`" => "last_updated_by",
		"`exams_table`.`created_by_username`" => "created_by_username",
		"`exams_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`exams_table`.`id`',
		2 => 2,
		3 => '`exams_table`.`exam_date`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`exams_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"if(`exams_table`.`exam_date`,date_format(`exams_table`.`exam_date`,'%d/%m/%Y'),'')" => "exam_date",
		"`exams_table`.`exam_type`" => "exam_type",
		"`exams_table`.`created_by`" => "created_by",
		"`exams_table`.`created_at`" => "created_at",
		"`exams_table`.`last_updated_by`" => "last_updated_by",
		"`exams_table`.`created_by_username`" => "created_by_username",
		"`exams_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`exams_table`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "Subject Details",
		"`exams_table`.`exam_date`" => "Exam Date",
		"`exams_table`.`exam_type`" => "Exam Type",
		"`exams_table`.`created_by`" => "Created by",
		"`exams_table`.`created_at`" => "Created At",
		"`exams_table`.`last_updated_by`" => "Last Updated by",
		"`exams_table`.`created_by_username`" => "Created by username",
		"`exams_table`.`last_updated_by_username`" => "Last Updated By",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`exams_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"if(`exams_table`.`exam_date`,date_format(`exams_table`.`exam_date`,'%d/%m/%Y'),'')" => "exam_date",
		"`exams_table`.`exam_type`" => "exam_type",
		"`exams_table`.`created_by`" => "created_by",
		"`exams_table`.`created_at`" => "created_at",
		"`exams_table`.`last_updated_by`" => "last_updated_by",
		"`exams_table`.`created_by_username`" => "created_by_username",
		"`exams_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['subject_details' => 'Subject Details', ];

	$x->QueryFrom = "`exams_table` LEFT JOIN `subject_table` as subject_table1 ON `subject_table1`.`id`=`exams_table`.`subject_details` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'exams_table_view.php';
	$x->TableTitle = 'Exams - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`exams_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Subject Details', 'Exam Date', 'Exam Type', 'Created by', 'Created At', 'Last Updated by', ];
	$x->ColFieldName = ['id', 'subject_details', 'exam_date', 'exam_type', 'created_by', 'created_at', 'last_updated_by', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/exams_table_templateTV.html';
	$x->SelectedTemplate = 'templates/exams_table_templateTVS.html';
	$x->TemplateDV = 'templates/exams_table_templateDV.html';
	$x->TemplateDVP = 'templates/exams_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: exams_table_init
	$render = true;
	if(function_exists('exams_table_init')) {
		$args = [];
		$render = exams_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: exams_table_header
	$headerCode = '';
	if(function_exists('exams_table_header')) {
		$args = [];
		$headerCode = exams_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: exams_table_footer
	$footerCode = '';
	if(function_exists('exams_table_footer')) {
		$args = [];
		$footerCode = exams_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
