<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/students_table.php');
	include_once(__DIR__ . '/students_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('students_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'students_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`students_table`.`id`" => "id",
		"`students_table`.`name`" => "name",
		"`students_table`.`gender`" => "gender",
		"if(`students_table`.`dob`,date_format(`students_table`.`dob`,'%d/%m/%Y'),'')" => "dob",
		"`students_table`.`email`" => "email",
		"`students_table`.`phone`" => "phone",
		"`students_table`.`address`" => "address",
		"if(`students_table`.`admission_date`,date_format(`students_table`.`admission_date`,'%d/%m/%Y'),'')" => "admission_date",
		"`students_table`.`department`" => "department",
		"`students_table`.`course`" => "course",
		"`students_table`.`year`" => "year",
		"`students_table`.`created_by`" => "created_by",
		"`students_table`.`created_at`" => "created_at",
		"`students_table`.`last_updated_by`" => "last_updated_by",
		"`students_table`.`last_updated_at`" => "last_updated_at",
		"`students_table`.`created_by_username`" => "created_by_username",
		"`students_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`students_table`.`id`',
		2 => 2,
		3 => 3,
		4 => '`students_table`.`dob`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`students_table`.`admission_date`',
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`students_table`.`id`" => "id",
		"`students_table`.`name`" => "name",
		"`students_table`.`gender`" => "gender",
		"if(`students_table`.`dob`,date_format(`students_table`.`dob`,'%d/%m/%Y'),'')" => "dob",
		"`students_table`.`email`" => "email",
		"`students_table`.`phone`" => "phone",
		"`students_table`.`address`" => "address",
		"if(`students_table`.`admission_date`,date_format(`students_table`.`admission_date`,'%d/%m/%Y'),'')" => "admission_date",
		"`students_table`.`department`" => "department",
		"`students_table`.`course`" => "course",
		"`students_table`.`year`" => "year",
		"`students_table`.`created_by`" => "created_by",
		"`students_table`.`created_at`" => "created_at",
		"`students_table`.`last_updated_by`" => "last_updated_by",
		"`students_table`.`last_updated_at`" => "last_updated_at",
		"`students_table`.`created_by_username`" => "created_by_username",
		"`students_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`students_table`.`id`" => "ID",
		"`students_table`.`name`" => "Name",
		"`students_table`.`gender`" => "Gender",
		"`students_table`.`dob`" => "Dob",
		"`students_table`.`email`" => "Email",
		"`students_table`.`phone`" => "Phone",
		"`students_table`.`address`" => "Address",
		"`students_table`.`admission_date`" => "Admission Date",
		"`students_table`.`department`" => "Department",
		"`students_table`.`course`" => "Course",
		"`students_table`.`year`" => "Year",
		"`students_table`.`created_by`" => "Created by",
		"`students_table`.`created_at`" => "Created At",
		"`students_table`.`last_updated_by`" => "Last Updated by",
		"`students_table`.`last_updated_at`" => "Last Updated At",
		"`students_table`.`created_by_username`" => "Created by username",
		"`students_table`.`last_updated_by_username`" => "Last Updated By",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`students_table`.`id`" => "id",
		"`students_table`.`name`" => "name",
		"`students_table`.`gender`" => "gender",
		"if(`students_table`.`dob`,date_format(`students_table`.`dob`,'%d/%m/%Y'),'')" => "dob",
		"`students_table`.`email`" => "email",
		"`students_table`.`phone`" => "phone",
		"`students_table`.`address`" => "address",
		"if(`students_table`.`admission_date`,date_format(`students_table`.`admission_date`,'%d/%m/%Y'),'')" => "admission_date",
		"`students_table`.`department`" => "department",
		"`students_table`.`course`" => "course",
		"`students_table`.`year`" => "year",
		"`students_table`.`created_by`" => "created_by",
		"`students_table`.`created_at`" => "created_at",
		"`students_table`.`last_updated_by`" => "last_updated_by",
		"`students_table`.`last_updated_at`" => "last_updated_at",
		"`students_table`.`created_by_username`" => "created_by_username",
		"`students_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`students_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'students_table_view.php';
	$x->TableTitle = 'Students App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`students_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Name', 'Gender', 'Dob', 'Email', 'Phone', 'Address', 'Admission Date', 'Department', 'Course', 'Year', 'Created by', 'Created At', 'Last Updated by', 'Last Updated At', ];
	$x->ColFieldName = ['id', 'name', 'gender', 'dob', 'email', 'phone', 'address', 'admission_date', 'department', 'course', 'year', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/students_table_templateTV.html';
	$x->SelectedTemplate = 'templates/students_table_templateTVS.html';
	$x->TemplateDV = 'templates/students_table_templateDV.html';
	$x->TemplateDVP = 'templates/students_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: students_table_init
	$render = true;
	if(function_exists('students_table_init')) {
		$args = [];
		$render = students_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: students_table_header
	$headerCode = '';
	if(function_exists('students_table_header')) {
		$args = [];
		$headerCode = students_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: students_table_footer
	$footerCode = '';
	if(function_exists('students_table_footer')) {
		$args = [];
		$footerCode = students_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
