<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/timetable_table.php');
	include_once(__DIR__ . '/timetable_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('timetable_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'timetable_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`timetable_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"IF(    CHAR_LENGTH(`faculty_table1`.`id`) || CHAR_LENGTH(`faculty_table1`.`name`), CONCAT_WS('',   `faculty_table1`.`id`, ' ~ ', `faculty_table1`.`name`), '') /* Faculty Details */" => "faculty_details",
		"`timetable_table`.`room_details`" => "room_details",
		"`timetable_table`.`day`" => "day",
		"`timetable_table`.`start_time`" => "start_time",
		"`timetable_table`.`end_time`" => "end_time",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`timetable_table`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`timetable_table`.`start_time`',
		7 => '`timetable_table`.`end_time`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`timetable_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"IF(    CHAR_LENGTH(`faculty_table1`.`id`) || CHAR_LENGTH(`faculty_table1`.`name`), CONCAT_WS('',   `faculty_table1`.`id`, ' ~ ', `faculty_table1`.`name`), '') /* Faculty Details */" => "faculty_details",
		"`timetable_table`.`room_details`" => "room_details",
		"`timetable_table`.`day`" => "day",
		"`timetable_table`.`start_time`" => "start_time",
		"`timetable_table`.`end_time`" => "end_time",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`timetable_table`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "Subject Details",
		"IF(    CHAR_LENGTH(`faculty_table1`.`id`) || CHAR_LENGTH(`faculty_table1`.`name`), CONCAT_WS('',   `faculty_table1`.`id`, ' ~ ', `faculty_table1`.`name`), '') /* Faculty Details */" => "Faculty Details",
		"`timetable_table`.`room_details`" => "Room details",
		"`timetable_table`.`day`" => "Day",
		"`timetable_table`.`start_time`" => "Start time",
		"`timetable_table`.`end_time`" => "End time",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`timetable_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`subject_table1`.`id`) || CHAR_LENGTH(`subject_table1`.`subject_name`), CONCAT_WS('',   `subject_table1`.`id`, ' ~ ', `subject_table1`.`subject_name`), '') /* Subject Details */" => "subject_details",
		"IF(    CHAR_LENGTH(`faculty_table1`.`id`) || CHAR_LENGTH(`faculty_table1`.`name`), CONCAT_WS('',   `faculty_table1`.`id`, ' ~ ', `faculty_table1`.`name`), '') /* Faculty Details */" => "faculty_details",
		"`timetable_table`.`room_details`" => "room_details",
		"`timetable_table`.`day`" => "day",
		"`timetable_table`.`start_time`" => "start_time",
		"`timetable_table`.`end_time`" => "end_time",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['subject_details' => 'Subject Details', 'faculty_details' => 'Faculty Details', ];

	$x->QueryFrom = "`timetable_table` LEFT JOIN `subject_table` as subject_table1 ON `subject_table1`.`id`=`timetable_table`.`subject_details` LEFT JOIN `faculty_table` as faculty_table1 ON `faculty_table1`.`id`=`timetable_table`.`faculty_details` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'timetable_table_view.php';
	$x->TableTitle = 'Timetable - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`timetable_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Subject Details', 'Faculty Details', 'Room details', 'Day', 'Start time', 'End time', ];
	$x->ColFieldName = ['subject_details', 'faculty_details', 'room_details', 'day', 'start_time', 'end_time', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/timetable_table_templateTV.html';
	$x->SelectedTemplate = 'templates/timetable_table_templateTVS.html';
	$x->TemplateDV = 'templates/timetable_table_templateDV.html';
	$x->TemplateDVP = 'templates/timetable_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: timetable_table_init
	$render = true;
	if(function_exists('timetable_table_init')) {
		$args = [];
		$render = timetable_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: timetable_table_header
	$headerCode = '';
	if(function_exists('timetable_table_header')) {
		$args = [];
		$headerCode = timetable_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: timetable_table_footer
	$footerCode = '';
	if(function_exists('timetable_table_footer')) {
		$args = [];
		$footerCode = timetable_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
