<?php

// Data functions (insert, update, delete, form) for table timetable_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function timetable_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('timetable_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'subject_details' => Request::lookup('subject_details', ''),
		'faculty_details' => Request::lookup('faculty_details', ''),
		'room_details' => Request::val('room_details', ''),
		'day' => Request::val('day', ''),
		'start_time' => Request::val('start_time', ''),
		'end_time' => Request::val('end_time', ''),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('timetable_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		timetable_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function timetable_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function timetable_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('timetable_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: timetable_table_before_delete
	if(function_exists('timetable_table_before_delete')) {
		$args = [];
		if(!timetable_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `timetable_table` WHERE `id`='{$selected_id}'", $eo);

	// hook: timetable_table_after_delete
	if(function_exists('timetable_table_after_delete')) {
		$args = [];
		timetable_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='timetable_table' AND `pkValue`='{$selected_id}'", $eo);
}

function timetable_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('timetable_table', $selected_id, 'edit')) return false;

	$data = [
		'subject_details' => Request::lookup('subject_details', ''),
		'faculty_details' => Request::lookup('faculty_details', ''),
		'room_details' => Request::val('room_details', ''),
		'day' => Request::val('day', ''),
		'start_time' => Request::val('start_time', ''),
		'end_time' => Request::val('end_time', ''),
	];

	// get existing values
	$old_data = getRecord('timetable_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: timetable_table_before_update
	if(function_exists('timetable_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!timetable_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'timetable_table',
		backtick_keys_once($set),
		['`id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="timetable_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('timetable_table', $data['selectedID'], calculated_fields()['timetable_table']);

	// hook: timetable_table_after_update
	if(function_exists('timetable_table_after_update')) {
		if($row = getRecord('timetable_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!timetable_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('timetable_table', $selected_id);
}

function timetable_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('timetable_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('timetable_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('timetable_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('timetable_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_subject_details = Request::val('filterer_subject_details');
	$filterer_faculty_details = Request::val('filterer_faculty_details');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: subject_details
	$combo_subject_details = new DataCombo;
	// combobox: faculty_details
	$combo_faculty_details = new DataCombo;
	// combobox: day
	$combo_day = new Combo;
	$combo_day->ListType = 0;
	$combo_day->MultipleSeparator = ', ';
	$combo_day->ListBoxHeight = 10;
	$combo_day->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/timetable_table.day.csv')) {
		$day_data = addslashes(implode('', @file(__DIR__ . '/hooks/timetable_table.day.csv')));
		$combo_day->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($day_data))));
		$combo_day->ListData = $combo_day->ListItem;
	} else {
		$combo_day->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("SUN;;MUN;;TUE;;WED;;THU;;FRI;SAT"))));
		$combo_day->ListData = $combo_day->ListItem;
	}
	$combo_day->SelectName = 'day';

	if($hasSelectedId) {
		if(!($row = getRecord('timetable_table', $selectedId))) {
			return error_message($Translation['No records found'], 'timetable_table_view.php', false);
		}
		$combo_subject_details->SelectedData = $row['subject_details'];
		$combo_faculty_details->SelectedData = $row['faculty_details'];
		$combo_day->SelectedData = $row['day'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_subject_details->SelectedData = $filterer_subject_details;
		$combo_faculty_details->SelectedData = $filterer_faculty_details;
		$combo_day->SelectedText = (isset($filterField[1]) && $filterField[1] == '5' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_subject_details->HTML = '<span id="subject_details-container' . $rnd1 . '"></span><input type="hidden" name="subject_details" id="subject_details' . $rnd1 . '" value="' . html_attr($combo_subject_details->SelectedData) . '">';
	$combo_subject_details->MatchText = '<span id="subject_details-container-readonly' . $rnd1 . '"></span><input type="hidden" name="subject_details" id="subject_details' . $rnd1 . '" value="' . html_attr($combo_subject_details->SelectedData) . '">';
	$combo_faculty_details->HTML = '<span id="faculty_details-container' . $rnd1 . '"></span><input type="hidden" name="faculty_details" id="faculty_details' . $rnd1 . '" value="' . html_attr($combo_faculty_details->SelectedData) . '">';
	$combo_faculty_details->MatchText = '<span id="faculty_details-container-readonly' . $rnd1 . '"></span><input type="hidden" name="faculty_details" id="faculty_details' . $rnd1 . '" value="' . html_attr($combo_faculty_details->SelectedData) . '">';
	$combo_day->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_subject_details__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['subject_details'] : htmlspecialchars($filterer_subject_details, ENT_QUOTES)); ?>"};
		AppGini.current_faculty_details__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['faculty_details'] : htmlspecialchars($filterer_faculty_details, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(subject_details_reload__RAND__) == 'function') subject_details_reload__RAND__();
				if(typeof(faculty_details_reload__RAND__) == 'function') faculty_details_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function subject_details_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#subject_details-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_subject_details__RAND__.value, t: 'timetable_table', f: 'subject_details' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="subject_details"]').val(resp.results[0].id);
							$j('[id=subject_details-container-readonly__RAND__]').html('<span class="match-text" id="subject_details-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subject_table_view_parent]').hide(); } else { $j('.btn[id=subject_table_view_parent]').show(); }


							if(typeof(subject_details_update_autofills__RAND__) == 'function') subject_details_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'timetable_table', f: 'subject_details' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_subject_details__RAND__.value = e.added.id;
				AppGini.current_subject_details__RAND__.text = e.added.text;
				$j('[name="subject_details"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subject_table_view_parent]').hide(); } else { $j('.btn[id=subject_table_view_parent]').show(); }


				if(typeof(subject_details_update_autofills__RAND__) == 'function') subject_details_update_autofills__RAND__();
			});

			if(!$j("#subject_details-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_subject_details__RAND__.value, t: 'timetable_table', f: 'subject_details' },
					success: function(resp) {
						$j('[name="subject_details"]').val(resp.results[0].id);
						$j('[id=subject_details-container-readonly__RAND__]').html('<span class="match-text" id="subject_details-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subject_table_view_parent]').hide(); } else { $j('.btn[id=subject_table_view_parent]').show(); }

						if(typeof(subject_details_update_autofills__RAND__) == 'function') subject_details_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_subject_details__RAND__.value, t: 'timetable_table', f: 'subject_details' },
				success: function(resp) {
					$j('[id=subject_details-container__RAND__], [id=subject_details-container-readonly__RAND__]').html('<span class="match-text" id="subject_details-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=subject_table_view_parent]').hide(); } else { $j('.btn[id=subject_table_view_parent]').show(); }

					if(typeof(subject_details_update_autofills__RAND__) == 'function') subject_details_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function faculty_details_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#faculty_details-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_faculty_details__RAND__.value, t: 'timetable_table', f: 'faculty_details' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="faculty_details"]').val(resp.results[0].id);
							$j('[id=faculty_details-container-readonly__RAND__]').html('<span class="match-text" id="faculty_details-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=faculty_table_view_parent]').hide(); } else { $j('.btn[id=faculty_table_view_parent]').show(); }


							if(typeof(faculty_details_update_autofills__RAND__) == 'function') faculty_details_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'timetable_table', f: 'faculty_details' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_faculty_details__RAND__.value = e.added.id;
				AppGini.current_faculty_details__RAND__.text = e.added.text;
				$j('[name="faculty_details"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=faculty_table_view_parent]').hide(); } else { $j('.btn[id=faculty_table_view_parent]').show(); }


				if(typeof(faculty_details_update_autofills__RAND__) == 'function') faculty_details_update_autofills__RAND__();
			});

			if(!$j("#faculty_details-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_faculty_details__RAND__.value, t: 'timetable_table', f: 'faculty_details' },
					success: function(resp) {
						$j('[name="faculty_details"]').val(resp.results[0].id);
						$j('[id=faculty_details-container-readonly__RAND__]').html('<span class="match-text" id="faculty_details-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=faculty_table_view_parent]').hide(); } else { $j('.btn[id=faculty_table_view_parent]').show(); }

						if(typeof(faculty_details_update_autofills__RAND__) == 'function') faculty_details_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_faculty_details__RAND__.value, t: 'timetable_table', f: 'faculty_details' },
				success: function(resp) {
					$j('[id=faculty_details-container__RAND__], [id=faculty_details-container-readonly__RAND__]').html('<span class="match-text" id="faculty_details-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=faculty_table_view_parent]').hide(); } else { $j('.btn[id=faculty_table_view_parent]').show(); }

					if(typeof(faculty_details_update_autofills__RAND__) == 'function') faculty_details_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/timetable_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/timetable_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Timetable table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#subject_details').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#subject_details_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#faculty_details').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#faculty_details_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#room_details').replaceWith('<div class=\"form-control-static\" id=\"room_details\">' + (\$j('#room_details').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#day').replaceWith('<div class=\"form-control-static\" id=\"day\">' + (\$j('#day').val() || '') + '</div>'); \$j('#day-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#start_time').replaceWith('<div class=\"form-control-static\" id=\"start_time\">' + (\$j('#start_time').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#end_time').replaceWith('<div class=\"form-control-static\" id=\"end_time\">' + (\$j('#end_time').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('#start_time').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: false, showInputs: false, disableFocus: true, minuteStep: AppGini.config.timeFieldMinutesStep || 5 });";
		$jsEditable .= "\t\$j('#end_time').addClass('always_shown').timepicker({ defaultTime: false, showSeconds: true, showMeridian: false, showInputs: false, disableFocus: true, minuteStep: AppGini.config.timeFieldMinutesStep || 5 });";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(subject_details)%%>', $combo_subject_details->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(subject_details)%%>', $combo_subject_details->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(subject_details)%%>', urlencode($combo_subject_details->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(faculty_details)%%>', $combo_faculty_details->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(faculty_details)%%>', $combo_faculty_details->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(faculty_details)%%>', urlencode($combo_faculty_details->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(day)%%>', $combo_day->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(day)%%>', $combo_day->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['subject_details' => ['subject_table', 'Subject Details'], 'faculty_details' => ['faculty_table', 'Faculty Details'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(subject_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(faculty_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(room_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(day)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(start_time)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(end_time)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(subject_details)%%>', safe_html($urow['subject_details']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(subject_details)%%>', html_attr($row['subject_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subject_details)%%>', urlencode($urow['subject_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(faculty_details)%%>', safe_html($urow['faculty_details']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(faculty_details)%%>', html_attr($row['faculty_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(faculty_details)%%>', urlencode($urow['faculty_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(room_details)%%>', safe_html($urow['room_details']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(room_details)%%>', html_attr($row['room_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(room_details)%%>', urlencode($urow['room_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(day)%%>', safe_html($urow['day']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(day)%%>', html_attr($row['day']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(day)%%>', urlencode($urow['day']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(start_time)%%>', safe_html($urow['start_time']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(start_time)%%>', html_attr($row['start_time']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(start_time)%%>', urlencode($urow['start_time']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(end_time)%%>', safe_html($urow['end_time']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(end_time)%%>', html_attr($row['end_time']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(end_time)%%>', urlencode($urow['end_time']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(subject_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(subject_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(faculty_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(faculty_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(room_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(room_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(day)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(day)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(start_time)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(start_time)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(end_time)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(end_time)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('timetable_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('timetable_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('timetable_table');
		$rdata = $row;
	}
	$templateCode .= loadView('timetable_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: timetable_table_dv
	if(function_exists('timetable_table_dv')) {
		$args = [];
		timetable_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}